# Generated by Django 5.0.4 on 2024-04-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getid', models.CharField(max_length=50, unique=True)),
                ('get_nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
