"""
Django settings for primera_aplicaion_django project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

#libreria por defecto
from pathlib import Path

#importaciones de las librerias necesarias
import os


""" STATIC_URL= os.path.join(BASE_DIR,'/static/') """

#sugerencia e chat de sair
BASE_DIR=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# url de archivos estaticos
STATIC_URL= '/static/'
MEDIA_URL='/media/'
MEDIA_ROOT= os.path.join(BASE_DIR,"media")
STATIC_ROOT= os.path.join(BASE_DIR,"static")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qp5!d-=iy@9q-v8781w6u1wh($$rr&b(4f4i$5nb2$*(3l-o@w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
#! aqui ban los modulos o aplicaciones del proyecto como por ejemplo "appprimera_aplicacion_django"
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appprimera_aplicacion_django'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'primera_aplicaion_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['./appprimera_aplicacion_django'],#la ruta de donde estan los archivos templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'primera_aplicaion_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':'djongo',
        'NAME':'django_mongodb',
        'CLIENT':{
            'host':'mongodb+srv://gun45780:adso145780@cluster0.feqs5gd.mongodb.net/?retryWrites=true&w=majority'
        }

    }
}
"""  #! coneccion con mondobd local
        'ENGINE':'djongo',
        'NAME':'django_mongodb',
        'HOST':'localhost',
        'PORT':'27017'
"""


"""     #! coneccion con myqsl local
        'ENGINE': 'django.db.backends.mysql',# aqui puede ir cualquier base de datos por ejemplo pymongo
        'NAME': 'aplicacion_1_django',
        'USER': 'root',
        'PASSWORD':'',
        'HOST':'localhost',
        'PORT':'3306' """

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
